version: '3'
services:
  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: poket-nacos
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ~/nacos/logs/:/home/nacos/logs
      - ~/nacos/init.d:/home/nacos/init.d
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - app
  mysql:
    image: nacos/nacos-mysql:8.0.16
    container_name: poket-mysql
    restart: always
    env_file:
      - ./env/mysql.env
    ports:
      - 3306:3306
    volumes:
      - ~/mysql:/var/lib/mysql
    networks:
      - app
  redis:
    image: redis:5
    container_name: poket-redis
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - ~/redis/data:/data
    ports:
      - 6379:6379
    networks:
      - app
  cloud-auth:
    container_name: cloud-auth
    restart: always
    build:
      context: ../cloud-auth
      dockerfile: docker-config/Dockerfile
    ports:
      - '9401:9401'
    depends_on:
      - nacos
      - redis
    networks:
      - app
  cloud-gateway:
    container_name: cloud-gateway
    restart: always
    build:
      context: ../cloud-gateway
      dockerfile: docker-config/Dockerfile
    ports:
      - '9201:9201'
    depends_on:
      - nacos
      - redis
      - cloud-auth
    networks:
      - app
networks:
  app:
    external: true