server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    name: cloud-auth
  cloud:
    nacos:
      discovery:
        server-addr: poket-nacos:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: poket-redis
    password:
management:
  endpoints:
    web:
      exposure:
        include: "*"
