server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: poket-nacos:8848
    gateway:
      routes: # 配置路由路径
        - id: service-a-route
          uri: lb://service-a
          predicates:
            - Path=/service/**
          filters:
            - StripPrefix=1
        - id: cloud-auth-route
          uri: lb://cloud-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: cloud-auth-login
          uri: lb://cloud-auth
          predicates:
            - Path=/login
          filters:
            - PreserveHostHeader
        - id: cloud-auth-token
          uri: lb://cloud-auth
          predicates:
            - Path=/oauth/token
          filters:
            - PreserveHostHeader
        - id: cloud-auth-authorize
          uri: lb://cloud-auth
          predicates:
            - Path=/oauth/authorize
          filters:
            - PreserveHostHeader
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
          lower-case-service-id: true # 使用小写服务名，默认是大写OAuth2FeignClient
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://poket-auth:9401/rsa/publicKey' # 配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: poket-redis
    password:
secure:
  ignore:
    urls: # 配置白名单路径
      - "/actuator/**"
      - "/oauth/token"
      - "/oauth/authorize"
      - "/login"
      - "/gateway/**"
      - "favicon.ico"
